ANT_PHEROMONE_DEPOSIT_RATE_PER_SEC = 2.0
ANT_PHEROMONE_DEPOSIT_INTENSITY_DECAY_FACTOR_PER_SEC = 0.97
ANT_FOOD_PHEROMONE_DECAY_FACTOR_PER_SEC = 0.985
ANT_NEST_PHEROMONE_DECAY_FACTOR_PER_SEC = 0.985
ANT_MIN_PHEROMONE_INTENSITY = 0.01
ANT_MAX_PHEROMONE_INTENSITY = 1.0
ANT_SENSING_RANGE = 25.0
ANT_SENSING_ATTENUATION_GAIN = 2.0
ANT_MOVE_SPEED = 5.0
ANT_CHAOS_FACTOR = 0.1
ANT_HEADING_DELTA_MOMENTUM_FACTOR = 0.25
ANT_WIDTH = 3.0
ANT_LENGTH = 5.0
ANT_MAX_SEARCHING_TIME_IN_SEC = 90.0
ANT_COLLISION_AVOIDANCE_HEADING_INCREMENT = 0.15

NEST_SENSING_RADIUS = 5.0
NEST_WIDTH = 5.0
NEST_HEIGHT = 5.0
NEST_PHEROMONE_INTENSITY = 10.0

FOOD_WIDTH = 5.0
FOOD_HEIGHT = 5.0
FOOD_PHEROMONE_INTENSITY = 10.0
